const rules = [
    { bestPractice: 'DomainsNumber', priority: 3, effort: 3, impact: 4, wsgCategory: 'NR' },
    { bestPractice: 'AddExpiresOrCacheControlHeaders', priority: 4, effort: 3, impact: 4, wsgCategory: 'NR', wsgId: 'WD18' },
    { bestPractice: 'CompressHttp', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR', wsgId: 'WD17' },
    { bestPractice: 'DontResizeImageInBrowser', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR', wsgId: 'WD14' },
    { bestPractice: 'EmptySrcTag', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR' },
    { bestPractice: 'ExternalizeCss', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR' },
    { bestPractice: 'ExternalizeJs', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR' },
    { bestPractice: 'HttpError', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR' },
    { bestPractice: 'HttpRequests', priority: 4, effort: 3, impact: 4, wsgCategory: 'NR', wsgId: 'WD17' },
    { bestPractice: 'ImageDownloadedNotDisplayed', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR', wsgId: 'WD14' },
    { bestPractice: 'JsValidate', priority: 3, effort: 3, impact: 2, wsgCategory: 'NR' },
    { bestPractice: 'MaxCookiesLength', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR' },
    { bestPractice: 'MinifiedCss', priority: 4, effort: 3, impact: 4, wsgCategory: 'NR', wsgId: 'WD16' },
    { bestPractice: 'MinifiedJs', priority: 4, effort: 3, impact: 4, wsgCategory: 'NR', wsgId: 'WD16' },
    { bestPractice: 'NoCookieForStaticRessources', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR' },
    { bestPractice: 'NoRedirect', priority: 3, effort: 3, impact: 3, wsgCategory: 'NR' },
    { bestPractice: 'OptimizeBitmapImages', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR', wsgId: 'WD14' },
    { bestPractice: 'OptimizeSvg', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR', wsgId: 'WD14' },
    { bestPractice: 'Plugins', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR' },
    { bestPractice: 'PrintStyleSheet', priority: 3, effort: 4, impact: 3, wsgCategory: 'NR' },
    { bestPractice: 'SocialNetworkButton', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR' },
    { bestPractice: 'StyleSheets', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR' },
    { bestPractice: 'UseETags', priority: 9, effort: 9, impact: 9, wsgCategory: 'NR', wsgId: 'WD18' },
    { bestPractice: 'UseStandardTypefaces', priority: 4, effort: 3, impact: 4, wsgCategory: 'NR', wsgId: 'WD11' },
    { bestPractice: 'ModernImageFormats', priority: 4, effort: 3, impact: 4, wsgCategory: 'Web Development', wsgId: 'WD14' },
    { bestPractice: 'OptimizeFonts', priority: 3, effort: 3, impact: 3, wsgCategory: 'Web Development', wsgId: 'WD11' },
    { bestPractice: 'TrackingScripts', priority: 5, effort: 4, impact: 5, wsgCategory: 'Web Development', wsgId: 'WD15' },
    { bestPractice: 'NoExternalIframes', priority: 4, effort: 4, impact: 4, wsgCategory: 'NR' },
    { bestPractice: 'NoAutoplayVideo', priority: 4, effort: 3, impact: 4, wsgCategory: 'UX Design', wsgId: 'UX15' },
    { bestPractice: 'LazyLoadImages', priority: 4, effort: 2, impact: 4, wsgCategory: 'Web Development', wsgId: 'WD14' },
    { bestPractice: 'NoExcessivePreload', priority: 3, effort: 3, impact: 3, wsgCategory: 'NR' },
    { bestPractice: 'NoRenderBlockingResources', priority: 4, effort: 3, impact: 4, wsgCategory: 'Web Development', wsgId: 'WD16' },
    // WSG rules
    { bestPractice: 'ReducedMotion', priority: 4, effort: 2, impact: 5, wsgCategory: 'UX Design', wsgId: 'UX16' },
    { bestPractice: 'DarkModeSupport', priority: 3, effort: 3, impact: 5, wsgCategory: 'UX Design', wsgId: 'UX06' },
    { bestPractice: 'VideoSubtitles', priority: 3, effort: 4, impact: 3, wsgCategory: 'UX Design', wsgId: 'UX15' },
    { bestPractice: 'ResponsiveImages', priority: 4, effort: 3, impact: 7, wsgCategory: 'Web Development', wsgId: 'WD14' },
    { bestPractice: 'FontSubsetting', priority: 3, effort: 3, impact: 4, wsgCategory: 'Web Development', wsgId: 'WD11' },
    { bestPractice: 'GreenHosting', priority: 5, effort: 5, impact: 9, wsgCategory: 'Hosting & Infrastructure', wsgId: 'HIS01' },
    { bestPractice: 'Co2PerVisit', priority: 5, effort: 5, impact: 8, wsgCategory: 'Hosting & Infrastructure', wsgId: 'HIS06' },
];

module.exports = rules;
